package com.example.storynest.Follow

enum class FollowActionState {
    FOLLOWER_ACCEPT,
    FOLLOWER_MESSAGE,
    FOLLOWER_PENDING,
    FOLLOWING,
    MY_USER_ITEM,
    OTHER_USER_ITEM,
    OTHER_USER_PENDING,
    OTHER_USER_MESSAGE,
    OTHER_USER_ACCEPT,
    REMOVE_FOLLOWER
}